### ISSUE TITLE
DB Deployment Error

### ISSUE THREAD

**Issue by chz160** [DragonPrime/Legend-of-the-Green-Dragon#27]
During initial setup on a server running MariaDB 10.1.22 the following error occurs when deploying tables to the database. I've also attempted with with pure MySql as well. Same result.

From the "Table Synchronization Logs":
_Error: Specified key was too long; max key length is 767 bytes
CREATE TABLE untranslated (
intext blob NOT NULL ,
language varchar(10) NOT NULL ,
namespace varchar(255) NOT NULL ,
PRIMARY KEY (intext(200),language,namespace),
KEY language (language),
KEY intext1 (intext(200),language)) engine=INNODB_

Then during the version migration from initial to latest the following occurs:
_Version 1.1.2 Dragonprime Edition: 4 SQL statements...
Doing: 
Error: 'Duplicate column name 'lastpage'' executing 'ALTER TABLE accounts ADD lastpage VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL AFTER restorepage'._

**Comment by stephenKise** [comment]
Hey, I have tried multiple times to recreate this in MariaDB 10.2 - and I have failed to do so. However, there is a slight issue with default variables in lib/all_tables.php causing the server not to deploy on MariaDB 10.2. This issue is being fixed with the next commit!

For vanilla MySQL, I will go ahead and implement a fix later on. It's an issue with encoding, since the original source did not use UTF-8.
